<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything EMPTY>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1713441459992.1839703715.2608380"
		mipmaps_folder="trakem2.1713441459992.1839703715.2608380/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		first_mipmap_level_saved="0"
	>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="24023.0"
		layer_height="27894.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="5"
			 thickness="1.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="547"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999990139775989,0.0014042947801968717,-0.0014042947801968717,0.9999990139775989,20144.339895324658,24830.638484420735)"
				title="Tile_179.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_179.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="546"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.999984975721745,-0.005481635776020225,0.005481635776020225,0.999984975721745,18303.938427206464,24946.275100080344)"
				title="Tile_178.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_178.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="545"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999951587386707,-0.0031116714512741538,0.0031116714512741538,0.9999951587386707,16468.165649179646,25043.644198429192)"
				title="Tile_177.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_177.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="544"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999894416930671,-0.004595269566405006,0.004595269566405006,0.9999894416930671,14633.255527235817,25139.8395519003)"
				title="Tile_176.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_176.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="543"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999955155426928,-0.0029948112635128157,0.0029948112635128157,0.9999955155426928,12801.32923477142,25202.65245346339)"
				title="Tile_175.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_175.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="542"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999908087305697,-0.004287476458413899,0.004287476458413899,0.9999908087305697,10959.928555201968,25297.42194967383)"
				title="Tile_174.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_174.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="541"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999865728506547,-0.005182095946809276,0.005182095946809276,0.9999865728506547,9125.780397404951,25385.087703369354)"
				title="Tile_173.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_173.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="540"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999875771411074,-0.004984532421164803,0.004984532421164803,0.9999875771411074,7296.840833290409,25473.001880019197)"
				title="Tile_172.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_172.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="539"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.99997366672572,-0.007257124438686237,0.007257124438686237,0.99997366672572,5464.005206272065,25565.463113223286)"
				title="Tile_171.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_171.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="538"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999885039449732,-0.004794995088036837,0.004794995088036837,0.9999885039449732,3636.268142601155,25656.66232198511)"
				title="Tile_170.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_170.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="537"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999929667632967,-0.00375052315554506,0.00375052315554506,0.9999929667632967,1810.6339538713532,25746.147890363343)"
				title="Tile_169.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_169.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="536"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999537686785792,-0.009615638590678686,0.009615638590678686,0.9999537686785792,0.031056168407189944,25847.208546890677)"
				title="Tile_168.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_168.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="535"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999268784931883,0.012092876699466225,-0.012092876699466225,0.9999268784931883,20251.994046545064,23072.72254537208)"
				title="Tile_167.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_167.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="534"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999989388760799,0.0014567932983192012,-0.0014567932983192012,0.9999989388760799,18416.745302654082,23156.205959117633)"
				title="Tile_166.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_166.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="533"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999981570043306,-0.0019198926902818402,0.0019198926902818402,0.9999981570043306,16581.187579737914,23236.829078420076)"
				title="Tile_165.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_165.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="532"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999963287777706,-0.0027096920454606063,0.0027096920454606063,0.9999963287777706,14751.64236328201,23321.810570013608)"
				title="Tile_164.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_164.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="531"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999949279651552,-0.003184971579763075,0.003184971579763075,0.9999949279651552,12916.825626243686,23412.26612600743)"
				title="Tile_163.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_163.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="530"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999905031286397,-0.004358170777957717,0.004358170777957717,0.9999905031286397,11079.893490910868,23498.770271677837)"
				title="Tile_162.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_162.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="529"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.999988691033049,-0.004755818121960369,0.004755818121960369,0.999988691033049,9249.433701475955,23585.772304863887)"
				title="Tile_161.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_161.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="528"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999867097345134,-0.0051556138666366755,0.0051556138666366755,0.9999867097345134,7421.694115211401,23678.922380963984)"
				title="Tile_160.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_160.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="527"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999915359852654,-0.004114359953839433,0.004114359953839433,0.9999915359852654,5594.901130871578,23767.40648813874)"
				title="Tile_159.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_159.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="526"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.999974503540414,-0.00714088713696962,0.00714088713696962,0.999974503540414,3765.292912397258,23861.990104344997)"
				title="Tile_158.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_158.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="525"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999564756990182,-0.00932988250723852,0.00932988250723852,0.9999564756990182,1943.6702880742637,23955.84845003249)"
				title="Tile_157.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_157.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="524"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999178309204788,-0.012819181225208363,0.012819181225208363,0.9999178309204788,132.71633536941317,24065.713651020407)"
				title="Tile_156.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_156.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="523"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999718141901878,0.007508050691397553,-0.007508050691397553,0.9999718141901878,20365.58096064842,21299.410159495204)"
				title="Tile_155.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_155.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="522"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999947207881341,0.003249368532755276,-0.003249368532755276,0.9999947207881341,18536.740966127727,21374.54583183711)"
				title="Tile_154.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_154.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="521"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.999999984550795,-1.7577943558333967E-4,1.7577943558333967E-4,0.999999984550795,16703.266404767484,21461.41173282326)"
				title="Tile_153.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_153.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="520"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999960404917663,-0.0028140719233415816,0.0028140719233415816,0.9999960404917663,14870.590397511702,21543.85127382352)"
				title="Tile_152.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_152.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="519"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999956898693687,-0.002936024980362466,0.002936024980362466,0.9999956898693687,13037.229266398925,21624.854731259828)"
				title="Tile_151.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_151.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="518"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.999994603527104,-0.0032852574739393806,0.0032852574739393806,0.999994603527104,11205.830943412731,21710.082268396185)"
				title="Tile_150.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_150.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="517"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999952281629668,-0.003089280061098261,0.003089280061098261,0.9999952281629668,9371.520618700699,21795.281130244297)"
				title="Tile_149.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_149.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="516"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.999988301841109,-0.004836959885606935,0.004836959885606935,0.999988301841109,7540.796685555534,21888.109991448306)"
				title="Tile_148.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_148.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="515"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999795692772927,-0.006392263136031159,0.006392263136031159,0.9999795692772927,5714.731327909738,21977.472406611825)"
				title="Tile_147.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_147.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="514"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999731378834767,-0.007329632424146477,0.007329632424146477,0.9999731378834767,3881.864882747718,22072.976357852902)"
				title="Tile_146.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_146.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="513"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9999551863465465,-0.009467063887156634,0.009467063887156634,0.9999551863465465,2055.987913427948,22168.83665362948)"
				title="Tile_145.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_145.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="512"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9998819751234879,-0.01536345739580198,0.01536345739580198,0.9998819751234879,242.1929657600191,22278.425526847408)"
				title="Tile_144.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_144.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2048"
				o_height="2048"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="511"
				width="2048.0"
				height="2048.0"
				transform="matrix(0.9998302482322142,0.018424839752595564,-0.018424839752595564,0.9998302482322142,20491.745824346952,19505.687752723843)"
				title="Tile_143.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_143.tiff"