<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything EMPTY>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1713540236727.1775205211.2608380"
		mipmaps_folder="D:/Projects/IDENTIFY/Data/Figure 3/TrakEM/trakem2.1713540236727.1775205211.2608380/trakem2.mipmaps/"
		storage_folder="D:/Projects/IDENTIFY/Data/Figure 3/TrakEM/"
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		first_mipmap_level_saved="0"
	>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="5016.0"
		layer_height="5660.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="5"
			 thickness="1.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="37"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999967207238257,0.00256096497338023,-0.00256096497338023,0.9999967207238257,3676.2971922412553,4379.116347212802)"
				title="Tile_29.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_29.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="36"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999999688944522,2.494215202980179E-4,-2.494215202980179E-4,0.9999999688944522,2757.839223208544,4427.602895842455)"
				title="Tile_28.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_28.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="35"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999997243892019,-7.424429407337881E-4,7.424429407337881E-4,0.9999997243892019,1839.895795099228,4482.11681186402)"
				title="Tile_27.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_27.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="34"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999954651234952,-0.0030115996487479675,0.0030115996487479675,0.9999954651234952,919.0604241316353,4538.775230740535)"
				title="Tile_26.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_26.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="33"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999925060745926,-0.003871407322414726,0.003871407322414726,0.9999925060745926,-0.178936288379699,4637.669266833774)"
				title="Tile_25.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_25.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="32"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999847545730479,0.005521831352106689,-0.005521831352106689,0.9999847545730479,3739.7607740837307,3483.7217079082748)"
				title="Tile_24.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_24.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="31"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999995751787839,9.217604091305187E-4,-9.217604091305187E-4,0.9999995751787839,2825.7604017981407,3531.92062096697)"
				title="Tile_23.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_23.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="30"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999992586484834,-0.001217662713309257,0.001217662713309257,0.9999992586484834,1908.9008325205837,3580.5861107196743)"
				title="Tile_22.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_22.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="29"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999934077009076,-0.003631054216945906,0.003631054216945906,0.9999934077009076,988.9066921124906,3634.2035318719327)"
				title="Tile_21.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_21.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="28"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999643289176903,-0.008446353780982829,0.008446353780982829,0.9999643289176903,72.0234048755635,3714.457576857374)"
				title="Tile_20.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_20.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="27"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999801421644178,0.006302005778382546,-0.006302005778382546,0.9999801421644178,3805.794757607062,2605.4100844844725)"
				title="Tile_19.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_19.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="26"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999982772101742,0.0018562264634810657,-0.0018562264634810657,0.9999982772101742,2887.841791100088,2649.6295598743845)"
				title="Tile_18.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_18.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="25"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999999446099665,-0.0010525209561868265,0.0010525209561868265,0.999999446099665,1968.0754354860646,2696.0956902184016)"
				title="Tile_17.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_17.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="24"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999970427614848,-0.0024319679860138155,0.0024319679860138155,0.9999970427614848,1050.207657541524,2754.6297460203477)"
				title="Tile_16.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_16.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="23"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999809773352181,-0.006168060286847256,0.006168060286847256,0.9999809773352181,133.64537970472736,2819.318534049359)"
				title="Tile_15.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_15.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="22"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999799631861424,0.006330341716007491,-0.006330341716007491,0.9999799631861424,3856.000235950439,1786.9693033748908)"
				title="Tile_14.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_14.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="21"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999974221123369,0.0022706317801061454,-0.0022706317801061454,0.9999974221123369,2948.62182164998,1773.6943942489374)"
				title="Tile_13.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_13.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="20"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999999545533242,-9.533799397970448E-4,9.533799397970448E-4,0.999999545533242,2030.9325779165029,1826.6353445099066)"
				title="Tile_12.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_12.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="19"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999972306003936,-0.0023534637331092544,0.0023534637331092544,0.9999972306003936,1105.7926473828668,1921.519747636189)"
				title="Tile_11.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_11.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="18"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999850257343004,-0.005472504652430558,0.005472504652430558,0.9999850257343004,206.23266181280385,1898.721194284476)"
				title="Tile_10.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_10.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="17"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999817576089994,0.0060402358576823,-0.0060402358576823,0.9999817576089994,3934.329609046139,842.9218377265665)"
				title="Tile_09.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_09.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="16"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999967201071689,0.0025612057520850535,-0.0025612057520850535,0.9999967201071689,3015.817745274109,890.6780077909793)"
				title="Tile_08.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_08.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="15"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999994654153901,0.001034006254346171,-0.001034006254346171,0.9999994654153901,2100.4896130956217,925.1151638100259)"
				title="Tile_07.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_07.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="14"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999999951696232,9.828913251707169E-5,-9.828913251707169E-5,0.9999999951696232,1178.0691309936876,992.3229387832689)"
				title="Tile_06.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_06.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="13"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999891060872537,-0.004667730370873875,0.004667730370873875,0.9999891060872537,255.40420843426202,1076.3055489086328)"
				title="Tile_05.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_05.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="12"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999880649181885,0.004885695567349503,-0.004885695567349503,0.9999880649181885,3993.9098786447053,0.06827926155938258)"
				title="Tile_04.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_04.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="11"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999963746495348,0.0026927101193883955,-0.0026927101193883955,0.9999963746495348,3079.24998004403,17.680219224367647)"
				title="Tile_03.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_03.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="10"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999992658848551,0.0012117053069729772,-0.0012117053069729772,0.9999992658848551,2161.1153364689667,72.8976068672523)"
				title="Tile_02.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_02.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="9"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999988500958609,-0.0015165114426819466,0.0015165114426819466,0.9999988500958609,1238.2039286942827,161.8068313652616)"
				title="Tile_01.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_01.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="8"
				width="1024.0"
				height="1024.0"
				transform="matrix(1.0,0.0,-0.0,1.0,340.0,149.0)"
				title="Tile_00.tiff"
				links=""
				type="0"
				file_path="Tiles/Tile_00.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
	</t2_layer_set>
</trakem2>
