<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything EMPTY>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="trakem2_xml.xml.gz"
		unuid="1709656262170.120053057.2608380"
		mipmaps_folder="trakem2.1709656262170.120053057.2608380/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		first_mipmap_level_saved="0"
	>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="5064.0"
		layer_height="5675.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="5"
			 thickness="1.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="10"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999842390527475,0.005614414136641499,-0.005614414136641499,0.9999842390527475,3700.6841637085777,4401.733834102116)"
				title="Tile_29.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_29.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="9"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999909072729615,0.004264430958476598,-0.004264430958476598,0.9999909072729615,2776.665245043986,4448.466395946768)"
				title="Tile_28.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_28.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="8"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999956700531208,0.0029427665571244046,-0.0029427665571244046,0.9999956700531208,1853.777452147914,4499.371249635806)"
				title="Tile_27.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_27.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="37"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999985317809158,0.0017136032250615798,-0.0017136032250615798,0.9999985317809158,928.2693371658988,4553.625547443875)"
				title="Tile_26.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_26.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="36"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999996281387067,-8.623934416747447E-4,8.623934416747447E-4,0.9999996281387067,-0.1035154766838789,4652.15509818856)"
				title="Tile_25.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_25.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="35"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999773376211731,0.006732328280063646,-0.006732328280063646,0.9999773376211731,3768.013301387649,3500.7725347394157)"
				title="Tile_24.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_24.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="34"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999881943523795,0.004859131184416207,-0.004859131184416207,0.9999881943523795,2849.375352767735,3548.1549953245617)"
				title="Tile_23.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_23.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="33"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999924149151121,0.0038948828277983794,-0.0038948828277983794,0.9999924149151121,1927.7922207492663,3592.600643783556)"
				title="Tile_22.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_22.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="32"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999999227494028,0.0012429848540486523,-0.0012429848540486523,0.999999227494028,1001.1868959994156,3643.508690031955)"
				title="Tile_21.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_21.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="31"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999999460477561,-3.2848818081912415E-4,3.2848818081912415E-4,0.9999999460477561,77.91540139274929,3716.8069102223403)"
				title="Tile_20.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_20.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="30"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999717460399085,0.007517121915768213,-0.007517121915768213,0.9999717460399085,3835.603133479626,2618.8374167608877)"
				title="Tile_19.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_19.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="29"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999883761533679,0.00482157216583638,-0.00482157216583638,0.9999883761533679,2913.488697343268,2661.180955444516)"
				title="Tile_18.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_18.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="28"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999924780271542,0.0038786452675724677,-0.0038786452675724677,0.9999924780271542,1990.818370892897,2703.7442179988875)"
				title="Tile_17.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_17.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="27"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999966559570772,0.002586131215319071,-0.002586131215319071,0.9999966559570772,1067.276807110396,2755.6535032120446)"
				title="Tile_16.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_16.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="26"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999961475795927,0.002775756828962158,-0.002775756828962158,0.9999961475795927,144.43730496987868,2812.9395325864148)"
				title="Tile_15.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_15.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="25"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.99995244474616,0.009752345675671195,-0.009752345675671195,0.99995244474616,3892.430482841838,1797.2149213077278)"
				title="Tile_14.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_14.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="24"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999814179046951,0.006096215655284343,-0.006096215655284343,0.9999814179046951,2982.1674211610984,1772.4841417225946)"
				title="Tile_13.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_13.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="23"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999852099339365,0.005438741893198626,-0.005438741893198626,0.9999852099339365,2058.331900941996,1827.063913516918)"
				title="Tile_12.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_12.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="22"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999951043801855,0.0031290918270435878,-0.0031290918270435878,0.9999951043801855,1126.545324727993,1919.8824271167405)"
				title="Tile_11.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_11.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="21"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999906766466888,0.0043181731898503,-0.0043181731898503,0.9999906766466888,221.36624499825427,1887.7351707960374)"
				title="Tile_10.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_10.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="20"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999935841033151,0.01132756890621709,-0.01132756890621709,0.999935841033151,3977.0433388951433,844.5738134650012)"
				title="Tile_09.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_09.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="19"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999634468171148,0.008550147930598113,-0.008550147930598113,0.9999634468171148,3052.800086280477,887.4816351166396)"
				title="Tile_08.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_08.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="18"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999731423823967,0.007329018616079983,-0.007329018616079983,0.9999731423823967,2134.010207248502,917.5491359639909)"
				title="Tile_07.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_07.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="17"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999830544532486,0.005821581086885681,-0.005821581086885681,0.9999830544532486,1204.4426060420737,981.5120100534482)"
				title="Tile_06.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_06.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="16"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999944729570387,0.0033247639577047476,-0.0033247639577047476,0.9999944729570387,276.30564669948916,1058.3691133816892)"
				title="Tile_05.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_05.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="15"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999937620628115,0.01116937118121414,-0.01116937118121414,0.999937620628115,4040.9155292791875,0.31250312091617616)"
				title="Tile_04.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_04.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="14"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999651260142098,0.008351452292003925,-0.008351452292003925,0.9999651260142098,3123.9111049017747,3.0297804465853915)"
				title="Tile_03.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_03.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="13"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.9999791525745776,0.006457121357826259,-0.006457121357826259,0.9999791525745776,2200.1222213705396,57.80963962042142)"
				title="Tile_02.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_02.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="12"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999978394947354,0.006573403875769364,-0.006573403875769364,0.999978394947354,1272.1529298377775,145.654892510021)"
				title="Tile_01.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_01.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="11"
				width="1024.0"
				height="1024.0"
				transform="matrix(0.999987781047821,0.004949136637151241,-0.004949136637151241,0.999987781047821,368.4486389160156,121.12359619140625)"
				title="Tile_00.tiff"
				links=""
				type="4"
				file_path="Tiles/Tile_00.tiff"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1024"
				o_height="1024"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
	</t2_layer_set>
</trakem2>
